events {}

http {
    log_format upstream_only '$upstream_addr';

    upstream api_pool {
        server api1:8080;
        server api2:8080;
        server api3:8080;
    }

    server {
        listen 80;
        access_log /tmp/up.log upstream_only;

        location / {
            proxy_pass http://api_pool;
        }
    }
}
